travis:
  secure:
    BINSTAR_TOKEN: E4+CCW9i+CXvktdgqdBmzriEOqqSW6U35cLgQqwcZwildfkHl7wVk4XnY5pLDWJhdqNMXcKgZPSExWEUK0PkW0ddM0IiY7l5r30xa3xXhmxClsGDPguayt5ejw05FWU17l+IAfec0Do7SVAnCXQ4mRomG87azhOLN7B71dKxRR7PkWbeLvzHxNG67zMa6iOGS90pFkMagdHB8YHAJiAmwbMR8xs193vp+yAbGCBWNcNNkaw3KlPp00vlZ2kqp6QZ25sB2/MhoWxNAx7AxRKjWJbEQb58phiRTumJkJjOVZ5kh+3SDzT8ijZj4W7142aD/KGg+TwURHtbo0XtFXWhzXpBSt8r0j0mJU3wB2a+vPC1dNOaJVXQzVeJinXb0mp7MKw/YLz0pwXmSNdNL3vpVF+ksAEp1Eu7dS20piSqGEoQR7AYv535xKImTYx/fwfef7dHxS9ppZ5hjZVBA7I1MXBsPZ+ktsnN62seDAUmQZ4ObMIHG34ZmxuEjvNPJnLpHHmRiWCsLxlPyeAzwK2z0entlrHyJ0Pp5hmTigopaPoJ9U8lKh+Ag89NKJoe4ufSAvup4oisSHK7egQUIw6BEKUmD3f3SaozRrqOHjsBHjCASgnHSMh42ZJB6HldL8jPOT+6zIxcJU0yLUvmf5t8kBj+3AERL3Fjxqfcdi9PxIk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
